### ISSUE TITLE
UnsatisfiedLinkError

### ISSUE THREAD

**Issue by doudasek** [scottyab/rootbeer#35]
Time to time I receive crash reported in Fabric that library crashed.

`Fatal Exception: java.lang.UnsatisfiedLinkError: Couldn't load tool-checker from loader dalvik.system.PathClassLoader[dexPath=/data/app/com.myapp.example-2.apk,libraryPath=/data/app-lib/com.myapp.example-2]: findLibrary returned null`

       at java.lang.Runtime.loadLibrary(Runtime.java:355)
       at java.lang.System.loadLibrary(System.java:525)
       at com.scottyab.rootbeer.RootBeerNative.(SourceFile)
       at com.scottyab.rootbeer.RootBeer.checkForRootNative(SourceFile:305)
       at com.myapp.example.entity.DeviceConfig.com.scottyab.rootbeer.RootBeer.isRooted(SourceFile:2044)
       at com.myapp.example.entity.DeviceConfig.parseJson(SourceFile:359)
       at com.myapp.example.net.request.Request.prepareRequest(SourceFile:2197)
       at com.myapp.example.net.request.Request.execute(SourceFile:129)
       at com.myapp.example.service.AppStartService.onStartCommand(SourceFile:65)
       at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2833)
       at android.app.ActivityThread.access$2000(ActivityThread.java:159)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1419)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:176)
       at android.app.ActivityThread.main(ActivityThread.java:5419)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:525)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1046)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:862)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Devices and values provided by Fabric:**
ASUS_T00J 4.4.2 No rooted
K6000 Pro 6.0 No rooted
GT-I9300 4.3 No rooted
B1-810 4.4.4 No rooted
P400 4.1.2 Rooted

**Comment by stealthcopter** [comment]
I believe this is caused by the `tool-checker.so` file being missing from the final apk for your app for the specific architecture on these devices.

I'm not sure why this is happening, but first let's make sure that is the case. If you inspect the apk files you are generating it should be obvious if the library is missing. See below for how a generate apk should look.

> Build > Analyse APK > Select your app apk file

![apk_analyse](https://cloud.githubusercontent.com/assets/1211162/23878777/48e00f40-0841-11e7-9f44-5b43ff4088a6.png)

Notice how there is a .so file for each architecture type

**Comment by stealthcopter** [comment]
We should add a try/catch for java.lang.UnsatisfiedLinkError when creating the RootBeerNative object in order to prevent the RootBeer Library from crashing if the .so cannot be found or loaded for whatever reason. Will create a branch / PR to fix this shortly.

**Comment by doudasek** [comment]
@stealthcopter Thank you for reply. 

I have analyzed one of the production APK where the exception occurred and it seems the same as yours.

![snimek obrazovky 2017-03-28 v 7 50 26](https://cloud.githubusercontent.com/assets/16006256/24390761/4276ddc8-138b-11e7-973c-9f9db7b8881e.png)

**Comment by stealthcopter** [comment]
Hi @doudasek So I'm not completely sure why this was happening for you, as the .so files are clearly there, and if it was a simple case of the wrong version we would see a totally different error.

However I've made a pull request for a change that will prevent the app from crashing when the native library cannot be loaded. The library will return false (that the device is unrooted) if the native library cannot be loaded, but if you want to check if the library can be loaded you can call the new function `boolean rootbeer.canLoadNativeLibrary()`

**Comment by doudasek** [comment]
@stealthcopter Thank you very much!
