### ISSUE TITLE
Error in production with proguard 

### ISSUE THREAD

**Issue by francescogatto** [scottyab/rootbeer#76]
We have theese crashes in our app mobile, with activated proguard

`Fatal Exception: java.lang.UnsatisfiedLinkError: No implementation found for int com.scottyab.rootbeer.RootBeerNative.setLogDebugMessages(boolean) (tried Java_com_scottyab_rootbeer_RootBeerNative_setLogDebugMessages and Java_com_scottyab_rootbeer_RootBeerNative_setLogDebugMessages__Z)
       at com.scottyab.rootbeer.RootBeerNative.setLogDebugMessages(RootBeerNative.java)
       at com.scottyab.rootbeer.RootBeer.checkForRootNative(RootBeer.java:373)
       at com.scottyab.rootbeer.RootBeer.isRooted(RootBeer.java:45)
       at LoginActivity.onCreate(LoginActivity.java:136)
       at android.app.Activity.performCreate(Activity.java:5990)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
       at android.app.ActivityThread.access$800(ActivityThread.java:151)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5254)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
       at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)`

**Comment by stealthcopter** [comment]
@francescogatto I believe this is probably a bug that we've fixed, please update to the latest version: 0.0.7
